### ISSUE TITLE
PHP memcache

### ISSUE THREAD

**Issue by mlocher** [codeship/documentation#137]
Installing `memcached` directly via PECL fails because of missing dependencies. A workaround is provided below curtesy of @mikejestes

```bash
pecl download memcached-2.2.0 
tar zxvf memcached-2.2.0.tgz 
cd memcached-2.2.0/ 
phpize 
./configure --with-libmemcached-dir=no --disable-memcached-sasl 
make 
make install 
echo "extension=memcached.so" > /home/rof/.phpenv/versions/`php-config --version`/etc/conf.d/20-memcached.ini
phpenv rehash
```

**Comment by emanuelecasadio** [comment]
Thanks @mlocher, I had the same problem and I solved it with this workaround.

**Comment by mikejestes** [comment]
FWIW we are now installing with `pecl install memcached-2.0.1` which runs smoothly. It doesn't seem to stick in the dependencies cache though.

**Comment by jpirkey** [comment]
@mlocher 
```
echo "extension=memcached.so" > /home/rof/.phpenv/versions/`php-config --version`/etc/conf.d/20-memcached.ini
```

makes it a bit more universal.  Thanks for posting this!

**Comment by mlocher** [comment]
Updated the original posting, thanks for the heads up @jpirkey

**Comment by klarkc** [comment]
+1 This affects me

**Comment by Magentron** [comment]
For me with PHP 7.1 the following works, thanks to the work of @mlocher @jpirkey:

```pecl download memcached-3.0.4 
tar zxvf memcached-3.0.4.tgz 
cd memcached-3.0.4/ 
phpize 
./configure --with-libmemcached-dir=no --disable-memcached-sasl 
make 
make install 
echo "extension=memcached.so" > /home/rof/.phpenv/versions/`php-config --version`/etc/conf.d/20-memcached.ini
phpenv rehash
cd ..```
