### ISSUE TITLE
Broken link - Project Build Triggers

### ISSUE THREAD

**Issue by schinckel** [codeship/documentation#1447]
https://app.codeship.com/projects/:id/branches/edit

There is a link on that page to 
https://documentation.codeship.com/general/projects/build-triggers

This url does not exist.

**Comment by drewkitch** [comment]
@petra-sargent ^

**Comment by petra-sargent** [comment]
The correct url is: https://documentation.codeship.com/general/projects/build_trigger/

**Comment by drewkitch** [comment]
Thanks Petra, I recognized that as well after the ping. Got a pull request up that should resolve the issue shortly https://github.com/codeship/mothership/pull/6828 -- apologies for the fire drill.
