### ISSUE TITLE
Ruby Sass will be unmaintained as of 26 March 2019

### ISSUE THREAD

**Issue by drewkitch** [codeship/documentation#1454]
[Updated Ruby Sass Gem is communicating this post install message](https://app.codeship.com/projects/102044/builds/79416bb9-530b-42f0-b448-6b6c02b602de?line=fd16f4b9-87a2-484a-a279-372391c54b1a&service=documentation)

**Comment by joesiewert** [comment]
Waiting for https://github.com/jekyll/jekyll-sass-converter/pull/75 to be released

**Comment by bwalding** [comment]
This problem goes away with Rails 6.
