### ISSUE TITLE
Explain resetting the database.yml before deploying

### ISSUE THREAD

**Issue by mlocher** [codeship/documentation#175]
Currently there is custom magic in place to make Rails testing easier on Codeship. We overwrite the default `database.yml` file with a Codeship specific version. If this version is later deployed via a copy based deployment strategy this will lead to errors.

**Comment by CTDragon** [comment]
I was just noticing this exact problem. 

It seems like instead of replacing values, you could replace it with <%= ENV['PG_USER'] %> and call it a feature instead of a bug saying that these environment variables should be setup on the destination server.

**Comment by mlocher** [comment]
This is fixed for the integrated AWS deployments, still need to add a warning to other file based deployments.

**Comment by ghiculescu** [comment]
I noticed this also. My workaround has been to add

```
git reset --hard &> /dev/null
```

As a line in my test setup script.

**Comment by ghiculescu** [comment]
I came across this issue when trying to use [parallel_tests](https://github.com/grosser/parallel_tests) because referencing `ENV['TEST_ENV_NUMBER']` in the database.yml was causing Codeship to swap it out.

My solution was to add this line to my test setup commands:

```
git reset --hard &> /dev/null
```
