### ISSUE TITLE
MariaDB support?

### ISSUE THREAD

**Issue by irobayna** [codeship/documentation#205]
MariaDB schema is almost identical to mysql, one key difference is that MariaDB seems to be case insensitive when applying indexes.  Same schema loading that works on a MariaDB might fail on Mysql if you try to apply an index and use for instance different case for the table name (i.e: test Vs. Test)

My builds fail on ```bundle exec rake db:schema:load```

Easy fix on my part, but kind of a PIA.  

Any plans to fully support MariaDB in the future?

Thanks!

**Comment by mlocher** [comment]
We won't install MariaDB on the current build VMs, but we now have a Docker based, fully customizable platform available as well. See http://pages.codeship.com/docker for more information and to request and invitation.
