### ISSUE TITLE
chrome not reachable

### ISSUE THREAD

**Issue by varyonic** [codeship/documentation#226]
https://codeship.com/projects/12300/builds/5648571 failed with 'Selenium::WebDriver::Error::WebDriverError: chrome not reachable'  I thought chromedriver was installed and available?

**Comment by mlocher** [comment]
Ahoy @varyonic, could you send us a message via the in app messenger (or via support(at)codeship.com) and include a link to your build. Chrome (and Firefox) are already installed on the VMs, but you'd need to install the webdriver package for the programming language you are using.

**Comment by SamOh** [comment]
@mlocher. The chrome not reachable error persists in chodeship despite having a proper selenium python package installed. The tests rely on the chromedriver being installed on the codeship VMs. The error is inconsistent and only arises for random builds but goes away after rebuilding the same code. Our team has reached out to support several times and has received no response.

**Comment by brunofracalossi** [comment]
I'm facing exactly the same several times in codeship. also running more than 1 chrome thread in parallel.

**Comment by robertIngrum** [comment]
Same issue for us.  Unfortunately we're not able to find any solutions for this, and at this point we just expect that there's a chance we'll have to restart out builds.  Given each build takes ~40 minutes, this is a fairly big inconvenience.  Would love to get some back and forth on this.
