### ISSUE TITLE
Receiving a 503 trying to fetch repositories.json

### ISSUE THREAD

**Issue by jhensley** [codeship/documentation#243]
I'm trying to setup a new project tied to a GitHub repository. The repositories.json call keeps timing out and throwing a 503 after a minute or so.

Here's the console.log error as well as the feed trying to be fetched:

`https://codeship.com/repositories.json?provider=github&wizard_path=%2Fprojects%2F87588%2Fproject_setup_steps%2Fsetup_scm` Failed to load resource: the server responded with a status of 503 (Service Unavailable)

**Comment by jhensley** [comment]
This is from the CodeShip Admin UI.

**Comment by jhensley** [comment]
And for what it's worth ...
![image](https://cloud.githubusercontent.com/assets/482316/8344549/087c6270-1ab1-11e5-80da-94646a7be609.png)

**Comment by jhensley** [comment]
Resolved by granting access to one of my orgs that was missing it, then leaving some of the orgs I wasn't involved in anymore. Not sure if the issue was in the volume of organizations and repositories -- or if it was in lacking access.

**Comment by mlocher** [comment]
@jhensley could you provide me with a rough number of repositories you had access to while the call timed out?

**Comment by jhensley** [comment]
About 450
