### ISSUE TITLE
Add ability to disable deployment

### ISSUE THREAD

**Issue by dwilkie** [codeship/documentation#244]
Hi I've setup a deployment for Elastic Beanstalk, and I want to temporarily disable it. Currently there is no way to do this without deleting the deployment

**Comment by clemenshelm** [comment]
We're aware of this issue, thanks for letting us know! For the time being there is a workaround:

1. Edit the deployment pipeline settings
![bildschirmfoto 2015-06-30 um 11 14 54](https://cloud.githubusercontent.com/assets/141632/8427681/8a9145b6-1f19-11e5-9402-bf18c133d3f0.png)

2. Change the deployment branch name to something different
![bildschirmfoto 2015-06-30 um 11 15 19](https://cloud.githubusercontent.com/assets/141632/8427687/9b772954-1f19-11e5-8145-dfe3fa08edb8.png)

When you save the changes, the original branch won't be deployed anymore. As soon as you want to re-enable deployments, just edit the deployment pipeline settings and insert the original branch name again.

**Comment by dwilkie** [comment]
Ah thanks, this won't work in my case actually because I've got two deployments set up. One for Heroku and one for Elastic Beanstalk. But yeh, cool let us know when it's fixed.

**Comment by mlocher** [comment]
Ahoy, I'll close this issue as this repository only tracks changes and issues with our documentation, not with the application itself. Please follow up via email to support@codeship.com or via our in app messenger if you have any further questions!
