### ISSUE TITLE
Indicate CI_PULL_REQUEST behaviour

### ISSUE THREAD

**Issue by caiofbpa** [codeship/documentation#250]
Your documentation says CI_PULL_REQUEST is automatically set to `false`, but there's no documentation about when it gets set to something else (like the PR number).

**Comment by mlocher** [comment]
Ahoy, 

the variable is currently set to `false` at all times. Once we add the ability to build PRs from forked repositories we will take a look at it again and may change it's behaviour.

**Comment by lolmaus** [comment]
I need to report pull request to Coveralls so that it can provide its status back to GitHub. It does not involve forked repos.

You do have pull request info per build. Why don't you expose it as an env var?

**Comment by aconrad** [comment]
Same here, I need this information. The webhook sent from the repository provider (github/bitbucket) to Codeship certainly should contain the PR number.

**Comment by mlocher** [comment]
Hey everybody, 

we have that feature on on our radar and are tracking requests for it internally at the moment. 

I'm going to close this issue (as this isn't the right place to request new features for our application, see our [Contributing Guidelines](https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue)).

Feel free to open a topic on https://community.codeship.com/c/feedback if you have further feedback / want to request additional features for Codeship.

**Comment by ethangj** [comment]
Hey, there - a bit late, but I wanted to let y'all know that we now have this environment variable exposed on Codeship. :)
