### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Lemonade4400** [codeship/documentation#252]
Hi, I'm using codeship as heroku addin. At the moment I'm not able to login using heroku integration. I've tried also to login bypadding heroku without success. Can you delete my bitbucket account association (or delete my account at all) so i can try to restart from scratch?

Please get in touch with me in private so I can share private information account.

Thank you in advance

**Comment by mlocher** [comment]
Ahoy, could you please get in touch via support@codeship.com with the email address you use on Codeship, as well as the name of the repository? And if possible include the email address you see on https://codeship.com/user/edit when you login via Heroku as well. 

Thx!
