### ISSUE TITLE
Force push to master branch screws up status image

### ISSUE THREAD

**Issue by cgrail** [codeship/documentation#262]
I've pushed some commits to the master branch and the builds where failing. After that I've decided to move those commits to a feature branch to work later on them and have removed them from the master branch via "git rebase --interactive master~3".

Now the status of my master build in codeship is still red even though the master branch is back to the old state.
https://github.com/cgrail/github-chrome-fullname
https://codeship.com/projects/9da71260-ed3f-0132-7e77-0eee9d4772fa/status?branch=master

**Comment by mlocher** [comment]
Ahoy @cgrail, 

the last build for the `master` branch on that project is still red. So the badge is red as well. Did the force push trigger a new build on Codeship?

P.S.: This is not exactly the right place to request help, please open tickets via support@codeship.com instead!

**Comment by cgrail** [comment]
@mlocher the latest build on master is just red for codeship. That's because the current latest commit on master is an older commit. This new old latest commit was green previously and would still be green. But codeship doesn't recognize that an old already successful build commit is the newest latest commit.

TravisCI and CircleCI could both handle this case. See the badges in my repo.
https://github.com/cgrail/github-chrome-fullname

I thought I'll just give you a hint as I'm using your service for free. And the least thing I can do is to test your software and report bugs.
