### ISSUE TITLE
Do you support Cassandra? How do you use it?

### ISSUE THREAD

**Issue by alexflav23** [codeship/documentation#276]
Hi, 

We are evaluating Codeship as a main build tool for the organisation, but having some trouble activating a Cassandra database to run during the CI phase. Some of your tweets and other details claim you already support Cassandra but your documentation doesn't explicitly say anything about that

Could you point us to a valid reference on activating Cassandra?

Regards.

**Comment by mlocher** [comment]
Ahoy, 

the latest version from the official Apache repositories is installed on the build VMs and available via port `9160` by default. The CLI is available as well, so you could run the a command like the following

```bash
cassandra-cli  -host localhost -port 9160 -f cassandra_schema.txt
```

**Comment by alexflav23** [comment]
Hi,

cassandra-cli has been deprecated for roughly 2.5 years now. I'm trying to start Cassandra with `service cassandra start` but this fails with an error:
```
/etc/init.d/cassandra: 84: ulimit: error setting limit (Operation not permitted)
/etc/init.d/cassandra: 85: ulimit: error setting limit (Operation not permitted)
```

Normally this would indeed require `sudo` which I don't have on your boxes. How do you use this?

Regards.

**Comment by mlocher** [comment]
The instance is already running, you don't need to start it (and you'd need `sudo` access for that).

**Comment by michelson** [comment]
Hello , it seems that cassandra-cli is deprecated, and cqlsh is throwing errors, 

```
Traceback (most recent call last):
File "/usr/bin/cqlsh", line 116, in <module>
from cqlshlib import cqlhandling, cql3handling, pylexotron
ImportError: No module named cqlshlib
```

best

**Comment by patriciojofre** [comment]
To install cqlsh and cqlshlib, run the following command:

`pip install cqlsh`
