### ISSUE TITLE
Issues when installing local gem?

### ISSUE THREAD

**Issue by marceloeloelo** [codeship/documentation#278]
Hi,

I need to install a local version of a gem and get the VM to pick that gem when running `bundle` in a separate command, but I'm having troubles making that work.

Basically, if I run: 
```
> gem install vendor/gems/my_gem.gem 
> bundle install
```

The first command succeeds but the second one fails saying that `my_gem` couldn't be found in any of the sources. I had the same set up in a different CI working fine. Any thoughts?

Thanks!

**Comment by mlocher** [comment]
Ahoy, 

could you get in touch via support@codeship.com and include a link to your project on Codeship.com. The code itself looks fine, but without more details I can only guess.
