### ISSUE TITLE
Cannot access https://codeship.com/projects

### ISSUE THREAD

**Issue by avoivo** [codeship/documentation#284]
I am trying to log in with my github account and i am getting an alert that says 'You have already signed up as <myemail>. Please log in to your account.'

Also when i try to redirect to https://codeship.com/projects i am getting an alert that says 'Please sign in to proceed'

**Comment by mlocher** [comment]
Ahoy, 

I can't find a Codeship user registered to your GitHub account, could you get in touch via support@codeship.com and send us the email address configured on GitHub? If this address is already known, the above error message is shown as well, but you won't automatically be able to sign in via GitHub.

Best, 
Marko

P.S.: This repository hosts our documentation, it's not intended to be used to get support. If you have questions regarding our service, feel free to reach out via email or on Twitter to [@CodeshipSupport](https://twitter.com/CodeshipSupport)

**Comment by avoivo** [comment]
Ahoy Marko,

Thanks a lot for the reply. i will proceed with that.

**Comment by mlocher** [comment]
Awesome, thanks! :+1:
