### ISSUE TITLE
Pusher can't authenticate, when using GitHub login

### ISSUE THREAD

**Issue by mmuehlberger** [codeship/documentation#291]
I noticed that live updates are not working, when I'm logged in with GitHub. Everything else in Codeship works.

The Browser's error console shows that `https://codeship.com/pusher/auth` returns a 403 Forbidden error.

It works just fine, when I use an account with email/password sign in.

**Comment by mlocher** [comment]
Ahoy @mmuehlberger, is this still an issue? I tried to replicate, but wasn't able to do so.

**Comment by mmuehlberger** [comment]
Haven't looked into it after the initial report, but it seems fixed now. Thanks.

**Comment by mlocher** [comment]
Awesome, thanks. Let us know if this should happen again.
