### ISSUE TITLE
BitBucket not triggering again.

### ISSUE THREAD

**Issue by CharGomez** [codeship/documentation#292]
Hey good morning, we are still having problems with the Builds not triggering for BitBucket repositories, can you help us please ??

**Comment by bfosberry** [comment]
Hi Char, please email support@codeship.com for support issues. If you can provide the Codeship project you're having trouble with that will help us debug the issue. 

We have been noticing high latency on some bitbucket webhooks, however we will verify there are no issues on our side also.

**Comment by CharGomez** [comment]
Ok perfect already sent a email.
