### ISSUE TITLE
unable to download the ebook?

### ISSUE THREAD

**Issue by crquan** [codeship/documentation#303]
nothing happened after clicked this download? neither browser download happening, nor my email (gmail) received anything, either Inbox or Spam; are all of these broken?
http://resources.codeship.com/ebooks/orchestrate-containers-with-docker-compose
http://resources.codeship.com/ebooks/thank-you-why-containers-and-docker-are-the-future

**Comment by crquan** [comment]
sorry, the 2nd one shows a download link after submitted, but still not the 1st one, now download link, no email or spam received.

[1] http://resources.codeship.com/ebooks/orchestrate-containers-with-docker-compose
[2] http://resources.codeship.com/ebooks/thank-you-why-containers-and-docker-are-the-future

**Comment by mlocher** [comment]
Ahoy @crquan, 

thanks for getting in touch. We'll take a look at the setup for those pages and see what's going on there. Could you please get in touch with manual@codeship.com and he'll send you the two ebooks.

Please also note, that this repository hosts our documentation, it's not intended to be used to get support. If you have questions regarding our service, feel free to reach out via email at support@codeship.com or on Twitter to [@CodeshipSupport](https://twitter.com/CodeshipSupport).

**Comment by crquan** [comment]
I don't see the contact emails anywhere on website codeship.com ; if I knew that, wouldn't open this issue; even I can get it thru manual@, could you post it somewhere on the website codeship.com ? otherwise other guys will run into same problem; especially, thru this link is still unable to download the book

[1] http://resources.codeship.com/ebooks/orchestrate-containers-with-docker-compose

**Comment by mlocher** [comment]
Sorry, I made a mistake copy / pasting the email, please get in touch with manuel@codeship.com (I updated the address above as well). He'll email you the ebook.

I also just tried the formular in a recent version of Chrome and Firefox and received the download link via email within a couple minutes.
