### ISSUE TITLE
Bitbucket Build status api

### ISSUE THREAD

**Issue by stereodenis** [codeship/documentation#311]
Here is [Bitbucket Build status api](http://blog.bitbucket.org/2015/11/18/introducing-the-build-status-api-for-bitbucket-cloud/)
https://confluence.atlassian.com/bitbucket/integrate-your-build-system-with-bitbucket-cloud-790790968.html
How to integrate it with CodeShip?

**Comment by mlocher** [comment]
Ahoy @stereodenis, 

we do have plans to integrate with the new Build Status API, but I can't share an ETA.

Please also note, that this repository is not the correct place to open feature requests (unless they are documentation related) or bug reports for the software. Feel free to reach out to support@codeship.com in those cases.

Thanks, 
Marko

**Comment by pv8** [comment]
Hi @mlocher!
I've wrote a Python script to try to integrate with [Bitbucket statuses/build API](https://confluence.atlassian.com/bitbucket/statuses-build-resource-779295267.html) myself, but I got an error regarding the availability of **[SNI extension to TLS](https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
SNIMissingWarning)** in Codeship environment:

```sh
/home/rof/.virtualenv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
SNIMissingWarning
/home/rof/.virtualenv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
InsecurePlatformWarning
```

BTW, the script **works** fine when I run it locally. Here is an excerpt of the script:
```python
import os
import requests

(...)

BITBUCKET_API_URL = "https://api.bitbucket.org/2.0/repositories" \
                    "/%(owner)s/%(repo_slug)s/commit/%(revision)s" \
                    "/statuses/build"
(...)

def _post(payload):
    api_call_url = BITBUCKET_API_URL % {
        'owner': REPO_OWNER,
        'repo_slug': REPO_NAME,
        'revision': os.getenv('CI_COMMIT_ID')
    }
    resp = requests.post(api_call_url,
                         auth=(BITBUCKET_API_KEY, BITBUCKET_API_SECRET),
                         json=payload)
```
