### ISSUE TITLE
PostgreSQL port overwrite command

### ISSUE THREAD

**Issue by Valve** [codeship/documentation#319]
The PG documentation says that in order to connect to a PG 9.4, one must overwrite the port with:

```
sed -i "s|5432|5434|" "config/database.yml"
```

is this command correct?

On OSX and Linux this returns: 

```
sed: 1: "config/database.yml": command c expects \ followed by text
```

The version that is working for me is: 

```
sed "s/5432/5434/" "config/database.yml" > config/database.yml.new
mv config/database.yml.new config/database.yml
```

**Comment by mlocher** [comment]
The command mentioned by you works with `sed (GNU sed) 4.2.2`, which is installed on the build VMs (which are based on Ubuntu Trusty)

For the version installed on OS X you'd need to modify it to include a zero-length extension after the `-i` switch like so:

```shell
sed -i "" "s|5432|5434|" "config/database.yml"
```

(The first character after a `s` command is always the delimiter, as a forward slash is often used in the pattern / replacement itself, we're using a pipe here, but in the end it's up to you)

**Comment by Valve** [comment]
thanks :)

**Comment by mlocher** [comment]
You're welcome :) The joys of different versions of standard tooling on different systems :D
