### ISSUE TITLE
Specifying branches to build or ignore.

### ISSUE THREAD

**Issue by robKitson** [codeship/documentation#320]
I noticed that there is a feature in the deployment section that allows one to specify what branch(es) to deploy. I'm wondering if it's possible to specify which branches are watched/ignored for builds?

For example, I'd like to create a build for our master branch and our qa branch, but I'd also like a build that watches ALL other branches.

Is this possible?

Thanks,
Rob

**Comment by mlocher** [comment]
Ahoy, each push to your remote repository will trigger a build and run the setup and test commands. Only the branches you configured explicitly will run deployments (and only if all previous steps are green).

There is currently no way to not trigger builds for specific branches, though you can exclude individual commits by haveing `--skip-ci` in the commit summary. See https://codeship.com/documentation/continuous-integration/skipping-builds/ and https://codeship.com/documentation/faq/limit_builds/ for more information.

P.S.: This issue tracker is for documentation related issues only (as stated in the Contributing document at https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue) Please open a new issue with our support team via email to support@codeship.com in those cases.

**Comment by msylvestre** [comment]
Hi guys, is it me, or --skip-ci hasn'T been implemented on a tag comment ?  Everytime I tag a version it trigger a build and I can't find how to prevent that
