### ISSUE TITLE
Support PHP7

### ISSUE THREAD

**Issue by frodeknutsen** [codeship/documentation#321]
You currently only support 5.3, 5.4, 5.5 and 5.6. Now that 7.0 has been out for a couple of months (almost), shouldn't you be supporting this version?

**Comment by mlocher** [comment]
Ahoy @frodeknutsen, we will add support for PHP7 once it's ready. As the php-build project (which we are using to build the versions available on the build VMs) removed support for PEAR and PECL with one of their recent updates, we need to look for workarounds to get those back first.

Please note, that this is our documentation project and it's issue tracker is not the correct place to get help regarding use of Codeship and it's services as noted in our [Contributing](https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue) document.

**Comment by vanlooverenkoen** [comment]
Any updates?
