### ISSUE TITLE
Modulus deploy fails with SSL

### ISSUE THREAD

**Issue by yogiben** [codeship/documentation#325]
Have same issue on 2 different projects. Does not fail when using http, but when url is https, produces the following error 6 times.

```
Trying (1 of 6) 'wget  --output-document=/dev/null https://bitwa.la'
--2016-02-03 12:44:40--  https://bitwa.la/
Resolving bitwa.la (bitwa.la)... 37.153.100.41
Connecting to bitwa.la (bitwa.la)|37.153.100.41|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-02-03 12:44:42 ERROR 500: Internal Server Error.
```

**Comment by mlocher** [comment]
Could you try running the following command via a SSH debug build? Judging from the log output and the error I'm guessing that the app isn"t ready yet and thus throws the error message.

```
check_url https://bitwa.la
```

The only way to work around this is by either decreasing startup time or disabling the check and adding a script based deployment to run the check manually after `sleep`'ing a certain amount of time.

P.S.: as noted in our [CONTRIBUTING](https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue) guidelines, this repository isn't really the right place to ask support related questions. Please get in touch via email instead.

**Comment by yogiben** [comment]
@mlocher I'd agree, but for the following:
* non-ssl stage versions of 2 apps working
* app is running in the browser while failing 6 `check_url`s

Started a conversation on support, but... can I ask why you don't want bugs logged here? Github is public, emails are private. You're creating a great resource for free here.
