### ISSUE TITLE
Feature Request - Add Github link to Slack notifications

### ISSUE THREAD

**Issue by tfeak** [codeship/documentation#328]
It would be nice to be able to go directly to a GitHub change set from the Slack notification messages, instead of having to go to CodeShip first. This is valuable to teams that don't want/need to provide user accounts to CodeShip for all team members that may subscribe to the Slack notifications.

It also avoids the need to log into codeship, just to get to Git.

**Comment by AlexTi** [comment]
@tfeak Thanks for the request. We want to improve our notifications in the future. I added your feedback to the list of requirements.
