### ISSUE TITLE
Too many open files on cassandra

### ISSUE THREAD

**Issue by patriciojofre** [codeship/documentation#329]
When i run specs it's fails and raise an error: **too many open files error**
 ![screen shot 2016-02-04 at 23 25 55](https://cloud.githubusercontent.com/assets/4438095/12836479/16970c3c-cb98-11e5-9238-bbbef2630c4b.png)

In casandra docs suggest increment the file descriptor but i haven't sudo permission for do this.

any solution?

**Comment by mlocher** [comment]
Hey @patriciojofre, sorry for the incredible slow reply times. Is this still an issue? If so, could you open a post on https://community.codeship.com/
