### ISSUE TITLE
Unable to access codeship project/build for GitHub repository which I own... :-(

### ISSUE THREAD

**Issue by nelsonic** [codeship/documentation#334]
Hi Codeship Team,
Don't know if this is the right place to ask this question, hope you can help.

We have a GitHub project that we are trying to configure to use Codeship: https://github.com/dwyl/learn-aws-lambda

For some reason the build does not work see: https://github.com/dwyl/learn-aws-lambda/pulls?q=is%3Apr (*all crosses*)
attempting to click on one of the "crosses" e.g: https://codeship.com/projects/130679/builds/11910719 which apparently I don't have access to.

![codeship-you-cant-access-this-page](https://cloud.githubusercontent.com/assets/194400/12959541/bc08d930-d02e-11e5-9de1-bd7938d2b33d.png)

> I am the ***owner*** of the GitHub Organisation to which the Project belongs, why can I not *access* the build...?! Are the builds not linked to GitHub Organisation ownership? (*is there a* :bug: *in your GitHub Authentication...?*)

**Comment by mlocher** [comment]
Ahoy, 

first, this is not the correct place to submit questions or bug reports about the way Codeships service functions, as stated in the [CONTRIBUTING](https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue) document (which is linked to from the _New Ticket_ form).

As for your question, access permissions on GitHub and Codeship are completely separated. Each project on Codeship is connected to either a GitHub or a Bitbucket project. But this doesn't add each member with access to those repositories to the project on Codeship. There might be good reasons for somebody having access to the repository, but not being allowed to view builds on Codeship.

You can add another Codeship account to a project via the _Team_ settings page of the project and, if you're on an organization plan, you can manage access to projects on a team level (similar to GitHub teams for organization accounts).

Please ask the owner of the project on Codeship to invite you to the project.
