### ISSUE TITLE
Why is the build for a Public GitHub Repository not Publicly Viewable?

### ISSUE THREAD

**Issue by nelsonic** [codeship/documentation#335]
We set up CodeShip for our "Canary" (Public GitHub) project: https://github.com/numo-labs/aws-lambda-canary
The build is passing according to the "*badge*": [![CodeShip Status](https://codeship.com/projects/babc13f0-9cdb-0133-9aee-22509ada1533/status?branch=master)](https://codeship.com/projects/127276) but if anyone tries to click on the badge to view the build log/history, they see a "*Please sign in to proceed*" error message:

![code-ship-please-login](https://cloud.githubusercontent.com/assets/194400/12961035/5099102c-d036-11e5-8ec5-78f8d2d741ae.png)

Why?!
I understand that a lot of "*Corporate*" customers want to be secretive about their builds,
but this is an ***Open Source / Public*** Project on GitHub, why is the default to lock it away...?! :disappointed:

**Comment by mlocher** [comment]
Similar to #334, this is not the right place to submit a feature request or a bug report (unless it is a bug with the documentation itself).

We currently don't have public build logs available. We have a plan to support those in the future, but I don't have an ETA to share yet. For our current target audience public build pages simply weren't that important, compared to other features they needed.

If this means that Codeship is "fundamentally flawed", or if we are simply targeting a different user group is up to you.

**Comment by nelsonic** [comment]
@mlocher while I understand that the "Corporate" or "Enterprise" user group may not have requested this feature, I am working in an Enterprise (*Paying Customer*) and would like to have the option to make the build log for a *Public* repository viewable by anyone. Fairly certain that other enterprise customers who do Open Source (e.g: AirBnB, Uber, Facebook etc.) will have the same desire ... 
E.g: when I click on the

**Comment by mlocher** [comment]
I agree it would be a good feature to have, that's why we are tracking it as a feature request and plan to implement it. It just wasn't that important yet and though a few users asked about it, it wasn't something that was keeping them from using Codeship.

**Comment by jiayihu** [comment]
I'm working too for an Enterprise customer and I'd like to have public logs, simply because they don't care about public code in this case and the log can be shared in the team without requiring everyone to register and be granted access.
