### ISSUE TITLE
Pretty unit/integration test reports

### ISSUE THREAD

**Issue by cos** [codeship/documentation#336]
In my current setup codeship does nothing special for junit reports. It simply displays the terminal printout of their run. Is there a way to instruct codeship to use the test artifacts to generate prettier reports?

For context, see this quora question: https://www.quora.com/Which-hosted-continuous-integration-services-show-you-individual-Java-test-results

**Comment by mlocher** [comment]
We don't have any special treatment for junit in place. If there are other formatters available, you can modify the configuration during your build to use those (you'd need to install them as well). You can also generate HTML reports, but you'd need to take care of uploading them yourself. (Especially in case of build failures, see https://github.com/codeship/scripts/blob/master/utilities/ensure_called.sh for a possible approach).

P.S.: I'm closing this ticket as it is not in compliance with the [CONTRITBUTING](https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue) document

**Comment by cos** [comment]
Thanks for the quick answer!

Sorry for the non-compliant ticket but I couldn't find any other support link. If the functionality would be there and not documented, it would be compliant :-)
