### ISSUE TITLE
How do I cancel my account? 

### ISSUE THREAD

**Issue by nivanson** [codeship/documentation#337]
I have searched and looked into My Account pages and I cannot find how to cancel/remove my account.

**Comment by mlocher** [comment]
Head over to https://codeship.com/subscription (for a personal account, organization accounts have a similarly named _Manage Subscription_ settings page) and hit the red _Cancel_ button next to your current plan.

Please also note, that, according to [CONTRIBUTING](https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue) document of this repository, this is not the correct place to ask product related questions. Means to get in touch are mentioned in the document itself.

**Comment by tobsn** [comment]
there is still no delete account option - I was looking through all pages. free account, nothing to cancel, no delete anywhere.

**Comment by mlocher** [comment]
@tobsn please send us an email (from the same email your Codeship account is registered to) to support@codeship.com and we'll take care of it.

If you could include why you want to cancel your account that would be awesome, but I totally get it if you don't.
