### ISSUE TITLE
Link to tools used (jet in this case)

### ISSUE THREAD

**Issue by thomassnielsen** [codeship/documentation#343]
While reading [this tutorial](https://codeship.com/documentation/docker/docker-push/), the command `jet` is used several times, without ever being explained or linked to. At a minimum, there should be a link to [this installation page](https://codeship.com/documentation/docker/installation/#jet), but also preferably with a short explanation paragraph about what Jet is.

**Comment by ziahot935** [comment]
Add me

**Comment by mlocher** [comment]
Hey folks, I finally prepared a PR and we'll link to the installation document soon. Sorry for how long it took to respond to this ticket :(
