### ISSUE TITLE
Deploying to EB failing on uploading to S3.

### ISSUE THREAD

**Issue by benwurth** [codeship/documentation#350]
My tests are set to deploy the code to Elastic Beanstalk via your integrations on a successful build on the master branch. The deployment fails with this error when it tries to upload the code to S3: 
```
ImportError: cannot import name MD5_AVAILABLE
```
This seems to be a problem with your Elastic Beanstalk integrations. Is there anything I can do to work around this?

**Comment by mlocher** [comment]
Closing this in favor of the Zendesk ticket (as this ticket doesn't comply with [CONTRIBUTING](https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue))

**Comment by Heedster** [comment]
@benwurth Did you manage to fix this issue? If you were, could be please explain. I am having the same issue.

**Comment by mlocher** [comment]
@Heedster please create a topic with full details on the error on https://community.codeship.com/ instead.
