### ISSUE TITLE
Cucumber reporting charts

### ISSUE THREAD

**Issue by abansal85** [codeship/documentation#434]
Hey Guys, Hows it going ?

We were trying to evaluate codeship for our automation builds. One thing we could not find out to do was how to see reporting charts/graphs just like In jenkins. For example 

https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Test+Result+Pluginhttps://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Test+Result+Plugin

Do you guys know how to do it ?

Thanks

**Comment by mlocher** [comment]
That's not currently built into Codeship, you could, however, publish the generated result files (from Cucumber) to a remote server and analyze them with a 3rd party tool.
