### ISSUE TITLE
forwarding logs 

### ISSUE THREAD

**Issue by abansal85** [codeship/documentation#435]
Hey guys, hows it going?  I was just wondering if there is any way we could forward logs from codeship build jobs ( similar to logstash ). We were hoping to import logs to kibana. 

Thanks

**Comment by mlocher** [comment]
Hey @abansal85, as per our [Contributing Guidelines](https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue) this repository is not the correct place to ask for feature requests or submit general support related questions. Please reach out to us via support@codeship.com in those cases.

As for your question, no that's currently not possible. But we'd be happy to add that as a feature request via the email above (and yes, you'd need to submit it again, so we know how to get in contact if/once we decide to add this.)
