### ISSUE TITLE
Maven Proxy is refusing connections

### ISSUE THREAD

**Issue by florianeckerstorfer** [codeship/documentation#453]
We are using Maven to build our project on Codeship and we are currently experiencing failed builds. After some investigation we found out that the pre-configured proxy `10.0.3.1` (in the `~/.m2/settings.xml`) is refusing connections from the virtual machine. When we remove the proxy before building Maven our build works correctly.

**Comment by mlocher** [comment]
Hey @florianeckerstorfer, thanks for letting us know. I alerted our engineering team and they'll look into this and release an updated version of the build VMs. I'll update this as soon as the new image is live.

**Comment by mlocher** [comment]
If somebody else finds this topic: current workaround until the new build VM image is live: add the following line to your setup steps. 

```
rm -rf "${HOME}/.m2/settings.xml"
```

Be careful if you modify the configuration elsewhere in your builds.

**Comment by beanieboi** [comment]
Hey,

I'm really sorry that I broke this. We rolled out the fix a couple of hours ago. Everything should be back to normal.

Thanks!

**Comment by florianeckerstorfer** [comment]
Thanks, builds are working again

**Comment by facundofarias** [comment]
It worked! Thanks 👍
