### ISSUE TITLE
Meteor Documentation

### ISSUE THREAD

**Issue by schmidsi** [codeship/documentation#481]
Hi there

I created some guides at Stackoverflow Documentation about how to setup continuous testing & integration for Meteor apps with Codeship.

I think they might be useful for other Codeshippers as well.

Where would be the best place for them? I am happy to create a pull-request if you tell me, where I should put them.

Here are the links:
- [Basic Codeship Setup for Automated Testing](http://stackoverflow.com/documentation/meteor/6741/basic-codeship-setup-for-automated-testing#t=201609152000170432796)
- [Continuous Deployment to Galaxy from Codeship](http://stackoverflow.com/documentation/meteor/6743/continuous-deployment-to-galaxy-from-codeship#t=201609152000174997169)
- [Use Private Meteor Packages on Codeship](http://stackoverflow.com/documentation/meteor/6742/use-private-meteor-packages-on-codeship#t=201609152005012027808)

**Comment by mlocher** [comment]
Hey @schmidsi, that's awesome. Thanks so much for investing the time to write those.

If you could prepare a PR, that would be great, could you add it to the `_posts/languages` folder (not a great name for the folder, but the category is actually called _Languages & Frameworks_) with a frontmatter similar to https://raw.githubusercontent.com/codeship/documentation/master/_posts/languages/2014-09-03-nodejs.md

Do you think they would all fit into a single article, or do you want to keep them separate?

**Comment by mlocher** [comment]
Closing this for now, we can always reopen the issue once we're ready to work on the Meteor documentation again.
