### ISSUE TITLE
Duplicate Access-Control-Allow-Origin headers

### ISSUE THREAD

**Issue by aleistra-arcane** [codeship/documentation#502]
Hello,

I came across the following issue in Chrome 53 on Windows 7 while running an Angular 2 client making use of the Codeship API.

> XMLHttpRequest cannot load https://codeship.com/api/v1/projects/#######.json?api_key=############################. The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://localhost:8000' is therefore not allowed access.

I have looked around for a solution from my end, but everything I have seen suggests that this is a server side issue.

**Comment by mlocher** [comment]
Hey @aleistra-arcane, as per our [Contributing Guidelines](https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue) this repository is not the correct place to ask for feature requests or submit general support related questions. Please reach out to us via support@codeship.com in those cases.
