### ISSUE TITLE
CodeShip Steps: Incorrect reference to number of steps

### ISSUE THREAD

**Issue by pcgeek86** [codeship/documentation#504]
In the documentation about CodeShip "steps," it says each "Group step" shares **four** directives. However, there are only three in the list (see screenshot below).

This is the document link: https://documentation.codeship.com/docker/steps/

![image](https://cloud.githubusercontent.com/assets/466713/19540906/d49fe1e8-961f-11e6-88bd-10a62a1babce.png)

I'm not sure if one of these conditions is true:

* There are supposed to be four steps, but one is missing from the list, **or**
* There are only supposed to be three steps in the list, making the "four" incorrect

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by thoughtkettle** [comment]
Hey @pcgeek86,

thanks for bringing this to our attention - it should now be fixed with #506.

Cheers,
Sanja

**Comment by pcgeek86** [comment]
@thoughtkettle Thanks!
