### ISSUE TITLE
Broken link - Working with environment variables

### ISSUE THREAD

**Issue by flashbackzoo** [codeship/documentation#521]
Hey,
The "Working with environment variables" link on the below screen is currently going to an error page.

![screen shot 2016-11-10 at 9 47 18 am](https://cloud.githubusercontent.com/assets/878176/20154189/0e6f0392-a72b-11e6-9271-92332490c447.png)

The URL is for the above screen is `https://app.codeship.com/projects/xxxxxxx/configure_environment`

**Comment by flashbackzoo** [comment]
Sorry - just realised this isn't actually a docs issue. Closing.

**Comment by mlocher** [comment]
Hey @flashbackzoo, it kind of is. We're going to create redirects for the old URL and will update the in app link to point to the new URL as well.

Thanks for reporting this 😍
