### ISSUE TITLE
Codeship documentation page is down

### ISSUE THREAD

**Issue by Gardezi1** [codeship/documentation#542]
Please don't create new issues on this repository when you experience issues with your builds on https://codeship.com, want to request new features for the CI system or have general questions on how to use https://codeship.com for your projects.

In all of the above cases, reach out to our support team at support@codeship.com or on Twitter at [@CodeshipSupport](https://twitter.com/CodeshipSupport).

If you are reporting an error in the documentation, please include the following:

- Exact location of error
- Proposed change, if any
- If the documentation error results in an error in your project, please include any relevant logs.

Thanks! 🚢

**Comment by Gardezi1** [comment]
Hello, guys, I'm trying to access your documentation page but the problem is it is not working. Can you please look into it and see what's going wrong 

![image](https://cloud.githubusercontent.com/assets/13199724/20340792/1d278510-ac05-11e6-92c1-cce7e749c38f.png)

**Comment by thoughtkettle** [comment]
Hi @Gardezi1,

https://documentation.codeship.com/ is working without problems, but we changed our design and have not redirected all links yet - could you please share the exact link that did not work so we can fix it?

Thank you,
Sanja

**Comment by Gardezi1** [comment]
Hi @thoughtkettle, 

Thanks for the quick response. I'm trying to access this link [ https://codeship.com/documentation/docker/installation]( https://codeship.com/documentation/docker/installation)

**Comment by thoughtkettle** [comment]
The new link for this is [https://documentation.codeship.com/docker/getting-started/installation/](https://documentation.codeship.com/docker/getting-started/installation/) - I'll make a redirect within this hour, so the old link will work as well.

Our search on the documentation pages works really well if you need to find something where a link is broken - and thank you for letting us know.
