### ISSUE TITLE
Incorrect "What to push?" link 

### ISSUE THREAD

**Issue by DominikPalo** [codeship/documentation#544]
Link "What to push?" on a dashboard for an empty project points to non-exist page `https://documentation.codeship.com/faq/codeship-badge/`
![image](https://cloud.githubusercontent.com/assets/1623257/20348143/62781fea-ac04-11e6-83d1-61e60b0f3acf.png)

**Comment by thoughtkettle** [comment]
Thank you, we'll fix this with the next PR in a few hours or earlier - for now [https://documentation.codeship.com/general/about/codeship-badge/](https://documentation.codeship.com/general/about/codeship-badge/) this is the correct link.
