### ISSUE TITLE
The documentation link doesn't work

### ISSUE THREAD

**Issue by mehdimahmoud** [codeship/documentation#584]
Please don't create new issues on this repository when you experience issues with your builds on https://codeship.com, want to request new features for the CI system or have general questions on how to use https://codeship.com for your projects.

In all of the above cases, reach out to our support team at support@codeship.com or on Twitter at [@CodeshipSupport](https://twitter.com/CodeshipSupport).

If you are reporting an error in the documentation, please include the following:

- Exact location of error
- Proposed change, if any
- If the documentation error results in an error in your project, please include any relevant logs.

Thanks! 🚢

**Comment by mlocher** [comment]
@mehdimahmoud Could you provide some more details? Where did you see the link to the documentation? If possible, where did it point to?

With the above information it is very hard for us to track down which link is currently broken.

**Comment by mehdimahmoud** [comment]
The referer page is : https://app.codeship.com/projects/191963/setup_jet

the link for documentation doesn't work :
https://documentation.codeship.com/docker (To *Define your environment*)
as well the service documentation doesn't work :
https://documentation.codeship.com/docker/services (to *Configure your
services*)
to configure the steps : https://documentation.codeship.com/pro/steps


[image: Images intégrées 1]


2016-12-22 17:47 GMT+00:00 Marko Locher <notifications@github.com>:

**Comment by mlocher** [comment]
Thanks, will create a PR to update those ASAP.

**Comment by mehdimahmoud** [comment]
Thank you.

2016-12-22 17:56 GMT+00:00 Marko Locher <notifications@github.com>:

**Comment by mlocher** [comment]
@mehdimahmoud Changes are live, you might need to clear the cache though.

Thanks again for alerting us about this, really great! Message me at marko@codeship.com if you'd like to get some stickers as a thank you.
