### ISSUE TITLE
Bitbucket hotfix changes not detected correctly

### ISSUE THREAD

**Issue by mathewparet** [codeship/documentation#585]
I integrated Codeship to work with my Bitbucket repo - https://bitbucket.org/paret/google-cloud-website (private repo)

Codeship works fine in normal cases, but when I did a hotfix it failed. I used SourceTree to make a hotfix (using git-flow) and applied the hotfix (to both `master` and `develop` as expected).
I pushed both changes to Bitbucket and the webhook was initiated.

I checked in Bitbucket and the hook sent information regarding the `master` branch update.

But someone it seems like Codeship detected only the `develop` branch change and not the `master` branch one. So no test was run on the master branch and so deployment also didn't happen.

Since it was a hotfix both the branches were updated at the same time. Is this the reason?

**Comment by mlocher** [comment]
Hey Matthew, 

please open a ticket on https://helpdesk.codeship.com for issues with the platform. As stated in our [Contributing Guidelines](https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue) this issue tracker is for documentation related issues only.

As for the issue at hand (and I would still ask you to open a ticket on our Helpdesk), please also take a look at whether Codeship is configured as a _Service_ or a _Webhook_ on Bitbucket. Please see https://documentation.codeship.com/general/projects/builds-are-not-triggered/#bitbucket for how to check this.
