### ISSUE TITLE
baffling non-feedback from the search feature

### ISSUE THREAD

**Issue by monkeypants** [codeship/documentation#662]
As a potential new user, I want to search the docs to see what you have to say about "terraform",
so that I can evaluate my cunning idea to move my junk to codeship.

Given I clicked the "documentation" link in the main menu
And then I click "search" (oh, there it is - lost 2 seconds looking for it :/)
When I type in search phrase "terraform"
And then I hit my enter key
Then I expect to see a page of search results, hopefully with a link saying "we have great terraform support, here's what you need to know..."

Instead, I got the document page again, exactly (as far as my eyes can tell) the same as what I got when I clicked the "documentation" link. No search results, no feedback. Maybe I did it wrong? so I did it again... and got the same result. Bah humbug.

**Comment by manualwise** [comment]
Sorry for the inconvenience! We're currently in the process of re-working our documentation. Currently, when there are no clear search results you simply get sent back to the main documentation page.  I agree that this is not great usability. We don't have a docs article on Terraform at the moment but you can use it on Codeship Pro. I'm also adding /cc @mlocher and @ethangj here who can give more insight about the new docs and Terraform support.

**Comment by monkeypants** [comment]
> Currently, when there are no clear search results you get sent back to the main documentation page. 

I guessed as much, yep it's a UX fail :)

**Comment by mlocher** [comment]
Hey @monkeypants, 

the page should look like the following screenshot, with the search results presented in an overlay on top of the documentation page.

Are you running any ad-blocker or anything else that might interfere with Javascript code on the page? And if so, could you disable those add-ons and try again?

If not, could you post a screenshot of the page you are seeing, including the URL field, as well as your browser version and the OS you are using?

![](http://d.pr/i/Qs46+)

**Comment by monkeypants** [comment]
Ah, privacy badger strikes again! Not an add blocker as such, surveillance reducer, but perhaps the same effect.

Ok, unless you decide privacy-badger users are a group that you need your site to work for, I guess you can close this ticket. Please do consider allowing yourself to be nudged in the direction of less surveilance-like behavior.

**Comment by ethangj** [comment]
Hey @monkeypants - We have greatly changed the UX of the docmentation pages since you left these valuable comments. I'm going to close this, but any new feedback you have is welcome.
