### ISSUE TITLE
Deployment command in Beanstalk deployment document not working

### ISSUE THREAD

**Issue by vijaydanielm** [codeship/documentation#70]
Hi,

In the "Deploy Script" section of https://codeship.io/documentation/continuous-deployment/deployment-to-elastic-beanstalk/, it is mentioned that "deploy_beanstalk.sh" should be entered in the script box. However, that doesn't work. I tried "./deploy_beanstalk.sh" as well to no avail. 

But, "sh deploy_beanstalk.sh" works fine! So, maybe, I'm wrong, or have some weird issues, but you might want to double check and update the documentation if necessary.

Also, it might we worthwhile mentioning that "chmod +x deployment_beanstalk.sh" has to be done prior to checking in (blog.lesc.se/2011/11/how-to-change-file-premissions-in-git.html).

Thanks. Got my first proper automated deployment on Elastic BeanStalk done within 3 hours (from setting up my AWS account to the automated deployment pipeline!) Could have been faster with the right documentation, but you guys are awesome anyways! :)

**Comment by mlocher** [comment]
Fixed by #196
