### ISSUE TITLE
Bad Link on CodeShip AWS Registry Docs

### ISSUE THREAD

**Issue by jiminikiz** [codeship/documentation#765]
- Exact location of error: [CodeShip AWS Registry Docs](https://blog.codeship.com/aws-registry) page refers to a [dockercfg](https://documentation.codeship.com/docker/dockercfg-services) docs hyperlink, but the `dockercfg` docs page is missing. It's under the heading **Authentication with ECR in Codeship**, second paragraph, first hyperlink.

- Proposed change, if any: Maybe it was meant to link to this page? [Builds & Configurations | Steps](https://documentation.codeship.com/pro/builds-and-configuration/steps/), though it seems to be a pro only feature.

**Comment by ethangj** [comment]
Hey @jiminikiz -

Thanks for pointing this out. We've gotten the post updated!
