### ISSUE TITLE
Typo on the 'Services Configuration' section

### ISSUE THREAD

**Issue by eugeniaguerrero** [codeship/documentation#841]
- Typo in this section on services file setup [here](https://documentation.codeship.com/pro/builds-and-configuration/services/#services-file-setup--configuration)
- Suggested change: from 'absense' to 'absence'

**Comment by mlocher** [comment]
Hey @eugeniaguerrero, 

thanks for spotting those and reporting them. We finally got around to prepare the PRs and fix the issues. The new documentation should go live within a couple of minutes.

Please let us know if we can help with anything else and happy shipping :)

**Comment by eugeniaguerrero** [comment]
Thanks so much @mlocher!
