### ISSUE TITLE
Ansible FAQ

### ISSUE THREAD

**Issue by mlocher** [codeship/documentation#89]
Include the following information to make ansible work

```bash
echo -e "[ssh_connection]\nssh_args = -o ForwardAgent=yes\n" > ~/.ansible.cfg
```

Also check if there is a way to use ansible with ControlMaster enabled on Codeship.

**Comment by dincho** [comment]
hey @mlocher did you found why ControlMaster cannot be enabled in Codeship?

**Comment by dincho** [comment]
@mlocher ?
