### ISSUE TITLE
Iink to none existing page

### ISSUE THREAD

**Issue by kirykr** [codeship/documentation#957]
Please don't create new issues on this repository when you experience issues with your builds on https://codeship.com, want to request new features for the CI system or have general questions on how to use https://codeship.com for your projects.

In all of the above cases, reach out to our support team at support@codeship.com or on Twitter at [@CodeshipSupport](https://twitter.com/CodeshipSupport).

If you are reporting an error in the documentation, please include the following:

- Exact location of error
   https://documentation.codeship.com/continuous-deployment/
- Proposed change, if any
  please fix it
- If the documentation error results in an error in your project, please include any relevant logs.

Thanks! 🚢

**Comment by mlocher** [comment]
@kirykr thanks for letting us know about this. Could you also point us to the site that links to https://documentation.codeship.com/continuous-deployment/ so that we can update the link itself?

**Comment by kirykr** [comment]
@mlocher i route to this link https://codeship.com/pricing/basic?hsCtaTracking=35b2d6a6-6c9c-49c0-b222-671b3a4e32d5%7Ce359ef0b-8218-48af-8100-dea7a6269a96
and in the box **Works out of the box** i click on the that say [Getting started](https://documentation.codeship.com/classic/)

**Comment by mlocher** [comment]
Thanks, I've let our Marketing team know and they'll fix the links soon. I'll keep this ticket open until those links are fixed and pointing to the correct pages.
